### ISSUE TITLE
Route/template memoization issue?

### ISSUE THREAD

**Issue by 6** [sarenji/solid#2]
Hey David, I can't get the `simple.coffee` example working correctly. I start it up with `coffee simple.coffee` and can access, say, [/user/123](http://localhost:9001/user/123) and this will correctly show `<p>Hi, 123!</p>`

However when I change the `id` value for the user, it continues to give me back that original ID. For example, visiting [/user/124](http://localhost:9001/user/124) will show `<p>Hi, 123!</p>` instead of the expected `<p>Hi, 124!</p>`

Do you know what might be going wrong here? I tried poking around the source a bit, but couldn't figure it out. Thanks!

**Comment by sarenji** [comment]
Wow, that was a pretty serious bug. Fixed!

Thanks!

**Comment by 6** [comment]
Awesome! It works great now
